### ISSUE TITLE
Bitwarden login - An error has occurred

### ISSUE THREAD

**Issue by 1Zedman** [bitwarden/desktop#1184]
### Steps To Reproduce

This error occurs for me when trying to log in through the website or the desktop client.
1.  Open Bitwarden
2. enter credentials
3. Error occurs

### Expected Result

Log in to Bitwarden and have access to my vault

### Actual Result

Error when trying to log in

### Screenshots or Videos

![bitwarden error](https://user-images.githubusercontent.com/95724156/145122034-e492ec19-f3ab-45bb-9395-9a8c2468c818.jpg)

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.29.1

**Comment by MartinWeberg** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/95745802/145182857-a94c04b3-2bdf-4839-afec-ad6a1979783a.png)

**Comment by charithperera** [comment]
Same happening on Android

**Comment by dArignac** [comment]
Also applies to the web vault.

**Comment by tomas-trtilek** [comment]
Confirming the very same issue - desktop, web, android.

**Comment by ragna-andersson** [comment]
Same issue on desktop, android.
"error has occured" on android when trying to login (was first promted to renew session)
Can still edit in desktop version, but get the red error message pictured above.

**Comment by Golfinho63** [comment]
Same issue on Android app.
Error: "ha ocurrido un error" when trying to login (was first promted to renew session).
Bitwarden desktop seems dont work when loading vault
I suggest everybody "export vault" if possible!

**Comment by dubrik11** [comment]
Good afternoon, I stopped running in Windows and Android

**Comment by dubrik11** [comment]
startup does not work

**Comment by dubrik11** [comment]
the same errors as described above

**Comment by dubrik11** [comment]
will this bug be fixed?

**Comment by djsmith85** [comment]
Thank you for your reports and being patient while we resolve this issue.

We would like to apologize for any inconvenience.

We experienced some server glitches this morning and engineering has been working on it. The incident has been resolved and everything should be back to normal. 

**If you are still encountering any issue, please make sure to log out from your account completely and log back in.**

The health status of our services can always be viewed at https://status.bitwarden.com/

**Comment by MartinWeberg** [comment]
> **If you are still encountering any issue, please make sure to log out from your account completely and log back in.**

I still have this issue. Cannot log out and login again since I was never logged in. And I cant login to logout ;-)

**Comment by djsmith85** [comment]
@MartinWeberg It took a while yesterday until all of our services we're fully functional again. Could you please try again and let me know if everything is working now. If not: Are you experiencing the same issue as detailed above or a different one. Please provide details and if needed we'll re-open this ticket.
