### ISSUE TITLE
Bitwarden v1.20.0 or later crashes on Windows 7

### ISSUE THREAD

**Issue by bchavez** [bitwarden/desktop#507]
## Describe the Bug

A recent update hosed my installation of Bitwarden desktop for windows.

![image](https://user-images.githubusercontent.com/478118/89373015-7be3f280-d69c-11ea-8095-cc8d650a3c80.png)

Attaching an instance of the VS 2019 debugger, slightly more details about the error:

> Unhandled exception at 0x00000000773E889D (ntdll.dll) in Bitwarden.exe: 0xC0000005: Access violation writing location 0x0000000000090C58. occurred

## Steps To Reproduce

1. On Windows 7, go to start menu.
2. Click on "Bitwarden"
![image](https://user-images.githubusercontent.com/478118/89373110-ae8deb00-d69c-11ea-9597-c0296ec6b4fd.png)

## Expected Result

The program should start with the login screen.

## Actual Result

![image](https://user-images.githubusercontent.com/478118/89373148-c6fe0580-d69c-11ea-8db8-d012849fc258.png)

## Environment

- Operating system: 
  * Windows 7, version 6.1 (Build 7601: Service Pack 1)
- Build Version (go to "Settings" → "About"):
  * Bitwarden v1.20.1

## Additional Context

Took a memory dump, ran `!analyze -v` in **WinDbg**:
(trying to be careful not to share PII)
```
0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************
.....
.....
FAULTING_THREAD:  000024cc
EXCEPTION_CODE: (HRESULT) 0x80000003 (2147483651) - One or more arguments are invalid
FAILURE_EXCEPTION_CODE:  80000003

FAILURE_IMAGE_NAME:  ntdll.dll

BUCKET_ID_IMAGE_STR:  ntdll.dll

FAILURE_MODULE_NAME:  ntdll

BUCKET_ID_MODULE_STR:  ntdll

FAILURE_FUNCTION_NAME:  RtlRaiseStatus

BUCKET_ID_FUNCTION_STR:  RtlRaiseStatus
```

I'll try to debug this some more after work tomorrow.

* Tried renaming the data folder: C:\Users\PROFILE\AppData\Roaming\Bitwarden so, I don't think it's any data or setting getting Bitwarden desktop stuck.

**Comment by cscharf** [comment]
@bchavez , are you running in the AMD64 x86 space or purely 32-bit x86? Also, seeing as that looks like a pointer exception any additional information you're able to find through the debugger would be helpful (thank you for that).

If you would feel more comfortable sharing information privately with me directly my email is cscharf at bitwarden dot com.

**Comment by bchavez** [comment]
Hi Chad,

Thanks for the details. I'll try working on a memory dump I can share. I did some tests and narrowed it down:
* :heavy_check_mark:  `1.19.0` works.
* :x: `1.20.0` fails.
* :x: `1.20.1` fails.

I believe I'm using AMD64, 64-bit processes:

![procexp64_3966](https://user-images.githubusercontent.com/478118/89477715-d6378e80-d742-11ea-9078-3414d807af94.png)

![taskmgr_3967](https://user-images.githubusercontent.com/478118/89477713-d59ef800-d742-11ea-95d8-7578176786de.png)

**Comment by bchavez** [comment]
So, I did a diff between `1.19.0` and `1.20.0`...

The changes in **`main.ts`** stood out to me and seemed suspect:

https://github.com/bitwarden/desktop/blob/c31de46b9e879b065be39e11ba32ae6ddeebd26a/src/main.ts#L112-L113

It looks like this change was part of #470 - Biometric support.

To test this theory, 
1. Extracted the `Bitwarden\resources\app.asar` file to `Bitwarden\resources\app`
2. Renamed `app.asar` to `app.asarx` to avoid electron from picking up the file.
3. Commented out the following lines in the `main.js` web packed file:

![image](https://user-images.githubusercontent.com/478118/89483678-77c5dc80-d751-11ea-98ec-91e35e325e5f.png)

4. Saved `main.js` file.
5. Started `Bitwarden` and :heavy_check_mark: now `1.20.0` works.

![image](https://user-images.githubusercontent.com/478118/89483738-a5ab2100-d751-11ea-9f4e-d8601dd2fa52.png)

---

### Conclusion
I suspect the native library import for biometric support from #470: `"@nodert-win10-rs4/windows.security.credentials.ui"` is making a native system call to a **Windows 10** API that is not available on **Windows 7**. You should be able to reproduce this crash if you try running **Bitwarden** `v1.20.0` or later on any **Windows 7** machine.

Thanks,
Brian Chavez

**Comment by cscharf** [comment]
Thanks @bchavez , you are correct, this module's addition has caused a few issues and crashes, however the issue was resolved for those users with Windows 7 (all) and Windows 10 (who did not have the appropriate VC++ dependencies installed). I suspect perhaps the loading of the module itself is successful on your machine as you're obviously set up for VC++ development, but then the API call itself under the covers is then failing.

If you note the line you commented out simply loads our wrapper/bootstrapper around that nodeRT module. This crash is not reproducible on any other Windows 7 machines we've tried, see: #495. Which leads me to believe it's because on your machine it is successfully loading the module and libraries necessary (which under normal circumstances would be missing) however the API calls are failing.

Is the crash itself when loading the module or when it's attempting to be used/called?

see: https://github.com/bitwarden/jslib/blob/master/src/electron/biometric.windows.main.ts#L52 (initialized/loaded)
see: https://github.com/bitwarden/jslib/blob/master/src/electron/biometric.windows.main.ts#L65 (called right after initialization/loading of the module to determine whether it will work on the given machine)

**Comment by bchavez** [comment]
Hi Chad,

I reverted my changes and tested the lines you indicated above.

Reverting all changes, the target locations were found in the web packed file:

![Notepad2_3974](https://user-images.githubusercontent.com/478118/89716136-55091300-d95f-11ea-9b55-2342fc72b070.png)

----

Commenting out either line as you've pointed out will fix the problem too:

### :heavy_check_mark: Works. No crash. Removing `getWindowsSecurityCredentialsUiModule`

![Notepad2_3972](https://user-images.githubusercontent.com/478118/89716158-8aadfc00-d95f-11ea-8e3b-205ed940e478.png)

-----

### :heavy_check_mark: Works. No crash. Removing `checkAvailabilityAsync`

![Notepad2_3973](https://user-images.githubusercontent.com/478118/89716153-7ff36700-d95f-11ea-9556-2f7d8b708b38.png)

----

Keeping them both methods intact will cause a crash; however. This test was on:
```
Version 1.20.1
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64
```

Thanks,
Brian

**Comment by cscharf** [comment]
Perfect, the PR submitted attached to this issue should resolve this for you once released.

**Comment by bchavez** [comment]
Got a notification for a Bitwarden 1.21 update.

Updated Bitwarden and Bitwarden still crashes in 1.21:

![image](https://user-images.githubusercontent.com/478118/93286555-63cbbc80-f78c-11ea-9767-cc5968574faa.png)

Extracted the ASAR file, commented out the following lines in `main.js`:

![image](https://user-images.githubusercontent.com/478118/93287075-78f51b00-f78d-11ea-875a-8283179f8777.png)

And it works again:

![image](https://user-images.githubusercontent.com/478118/93287114-8ca08180-f78d-11ea-9961-46bdf899a308.png)

This is still an issue.

**Comment by cscharf** [comment]
@bchavez , if you wrap those 2 lines in a `try {} catch {}` instead, does that also prevent the crash?

```javascript
try {
    const BiometricWindowsMain = __webpack_require__(17).default;
    this.biometricMain = new BiometricWindowsMain(this.storageService, this.i18nService);
} catch { }
```

**Comment by bchavez** [comment]
Hi @cscharf, the `try{} catch{}` doesn't prevent the crash. I think the fact that a thread makes any *attempt* at an undefined native API causes Bitwarden to crash:

![image](https://user-images.githubusercontent.com/478118/93371442-3a9c4200-f807-11ea-8f0f-72457da551d8.png)


I suspect a proper fix would look something like:

![image](https://user-images.githubusercontent.com/478118/93371976-12611300-f808-11ea-86a0-24489d700d4a.png)

**Comment by cscharf** [comment]
@bchavez , I've merged into `jslib` and `desktop` what I believe will resolve this, thanks for the working models and psuedo-code on suggested fix. I believe now, unless you're working with Windows 10, we'll not even attempt to load the biometrics support library (nodeRT) which should prevent the crash. Until that gets released with the next version you should be able to keep your modified version with those 2 lines commented out.

**Comment by bchavez** [comment]
Great news, recently updated to:
```
Version 1.22.2
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64
```
and the issue appears to be resolved on `win7` now. Thanks a bunch!
