### ISSUE TITLE
Close To Tray Doesn't Work With Ctrl-W Shortcut

### ISSUE THREAD

**Issue by Snuupy** [bitwarden/desktop#832]
## Describe the Bug

After enabling the close to tray option, Ctrl-W doesn't close to tray. This is a bug introduced in v1.25.0 and was previously working (Ctrl-W would close the app to tray instead of terminating the entire app process)

## Steps To Reproduce

1. Go to settings, enable close to tray option
2. Close the settings dialog
3. Press `Ctrl-W`
4. Notice that your app has now terminated instead of being closed to tray

## Expected Result

App should close to tray.

## Actual Result

Terminates app process entirely.

## Environment

- Operating system: Windows 10
- Installation method: [e.g. Downloaded from Bitwarden.com, Mac App Store / Microsoft Store, Homebrew, Snap] 
- Build Version (go to "Settings" → "About"): 1.25.1

## Additional Context

Bug was confirmed by a second user on matrix, third user on reddit.

Also broken on v1.25.0, works on 1.24.6.

https://www.reddit.com/r/Bitwarden/comments/momau5/desktop_app_ctrlw_bug/

**Comment by hwittenborn** [comment]
I'm having the same Issues on the Linux client, I'm not sure if it happened in previous versions or not though.

Here's the exact system info if it's relevant:

```
Version 1.25.1
Shell 11.3.0
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64
```

**Comment by Snuupy** [comment]
I downgraded to v1.24.6 while I wait for this issue to be resolved.

**Comment by cscharf** [comment]
This duplicates #714 and is resolved by https://github.com/bitwarden/desktop/pull/836

**Comment by Snuupy** [comment]
@cscharf does "next release" refer to or include v1.26.3? This issue is still present on Windows 10. I see https://github.com/bitwarden/desktop/pull/836 was pulled into master on April 13, 2021 and the build https://github.com/bitwarden/desktop/releases/tag/v1.26.0 was done May 12, 2021 but this is not fixed for me.

**Comment by eliykat** [comment]
Reopening this because @kendratodd said that this issue is still present, and we received a similar report on Gitter.

**Comment by Snuupy** [comment]
Hi, I'm the user that posted in Matrix/Gitter that `Ctrl-W` still ends the bitwarden desktop app on Windows 10, bitwarden v1.26.3.

**Comment by hwittenborn** [comment]
Doesn't appear to be working on v1.26.5 on the Linux release

**Comment by Snuupy** [comment]
This is still an issue in v1.32.1. Just tested it, still a bug.

**Comment by cscharf** [comment]
Thanks @Snuupy , I've removed the stale label and we'll keep this on our radar, appreciate the quick reply!
