### ISSUE TITLE
Folder and item lists do not load after unlocking

### ISSUE THREAD

**Issue by kriswillis** [bitwarden/desktop#894]
## Describe the Bug

After unlocking, the folder list shows "Loading…" indefinitely and the item list shows a spinner indefinitely. The dev tools console reports the following:

```
Error: Uncaught (in promise): TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Set (<anonymous>)
    at vault_groupings_component_GroupingsComponent.<anonymous> (groupings.component.ts:65)
    at Generator.next (<anonymous>)
    at fulfilled (folder-add-edit.component.ts:14)
    at ZoneDelegate.push.ZoneDelegate.invoke (vendor.js:132616)
    at Object.onInvoke (vendor.js:28582)
    at ZoneDelegate.push.ZoneDelegate.invoke (vendor.js:132615)
    at Zone.push.Zone.run (vendor.js:132373)
    at vendor.js:133121
    at ZoneDelegate.push.ZoneDelegate.invokeTask (vendor.js:132651)
    at resolvePromise (vendor.js:133062)
    at vendor.js:132969
    at rejected (view.component.ts:36)
    at ZoneDelegate.push.ZoneDelegate.invoke (vendor.js:132616)
    at Object.onInvoke (vendor.js:28582)
    at ZoneDelegate.push.ZoneDelegate.invoke (vendor.js:132615)
    at Zone.push.Zone.run (vendor.js:132373)
    at vendor.js:133121
    at ZoneDelegate.push.ZoneDelegate.invokeTask (vendor.js:132651)
    at Object.onInvokeTask (vendor.js:28570)
```

It *is* possible to search the vault in this state.

## Steps To Reproduce

1. Launch Bitwarden
2. Enter master password
3. Click Unlock

## Expected Result

Folders should be displayed in the left panel, all items should be displayed in centre panel.

## Actual Result

"Loading…" displayed indefinitely in the left panel, spinner displayed indefinitely in the centre panel.

## Screenshots or Videos

![bitwarden-error](https://user-images.githubusercontent.com/2786947/118292299-64aa1f00-b4d0-11eb-81af-c51456dd1e55.png)

## Environment

- Operating system: Xubuntu 20.04.2 LTS
- Installation method: Bitwarden-1.26.3-x86_64.AppImage downloaded from Bitwarden.com
- Build Version: 1.26.3

**Comment by b1n4ryj4n** [comment]
yeah i get the same error message today

OS: Windows 10 x64
Build Version 1.26.3

**Comment by gymbob721** [comment]
Same error yesterday. I uninstalled and reinstalled, that solved the problem yesterday. Today the problem.

**Comment by noi75** [comment]
Hi,

i have the same Problem..

OS: Windows 10 x64 20H2
Sehll 11.3.0
Rendrer 87.0.42.80.141
Build Version 1.26.3
Node 12.18.3
Architecture X64

**Comment by o-jc** [comment]
Same issue here,

OS: Windows 10 x64 20H2 
Version: 1.26.3
Shell: 11.3.0
Renderer: 87.0.4280.141
Node: 12.18.3
Architecture: x64

Website does not seem to exhibit the issue. The issue seemed to occur after leaving my computer on overnight (no sleep or hibernation settings are applied) and any basic fixes like signing out and in or computer restart do not resolve issue for me either.

**Comment by matthieuclegault** [comment]
Same issue here, 

OS Windows 10 x64 20H2
Version 1.26.3
Shell 11.3.0
Renderer 87.0.4280.141
Node 12.18.3
Architecture x64

Website & browser extension works perfectly. 
Happened after update when locking Bitwarden. 
Uninstall / reinstall did fix the issue at 1st but it came back the second I rebooted. 

![ls 1621339112](https://user-images.githubusercontent.com/36636632/118647006-dde69200-b7ae-11eb-9252-2a6d276c2b1b.png)

**Comment by mckartha** [comment]
I hit this same problem yesterday and when inspecting via the Developer Tools Console I see the same error as shown in the original post:

```
vendor.js:4565 ERROR Error: Uncaught (in promise): TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Set (<anonymous>)
    at vault_groupings_component_GroupingsComponent.<anonymous> (groupings.component.ts:65)
    at Generator.next (<anonymous>)
...
```

This error is occuring for me in Bitwarden desktop `Version 1.26.3 (526)` on Mac OS X 11.2.3.

Notably this folder "Loading ..." issue/error does *not* occur on the iOS app in either of the following versions:
*  the most recent version from 4 days ago, `Version: 2.10.0 (616)` on an iPad
* or in the 3 months older `Version 2.8.0 (449)` on an iPhone

Saying that this error does *not* occur, means that in both of these iOS versions, the Bitwarden folder tree displays as expected in both apps.  Also edits made to the folder tree (add/remove folder) on one app and then sync'ing the PW DB, allows the folder tree to display properly showing folder updates on the other app/device after pulling the most recent sync'd PW DB.

**Comment by derek-shnosh** [comment]
Experiencing the same issue with desktop client 1.26.3 on Win 10 (1909).

My temp fix has been to delete `%appdata%\Bitwarden` and then go through the login/2FA process again, then setup prefs how I want.

I do have folders/nested folders, and the only non-alpha chars in names are `_` or `-` (some start with `_`).

I found that if I simply log into the client and set preferences, I can close the client and relaunch it as many times as I want without experiencing this behavior... but if I log in and collapse all of my nested folders, *then* close and relaunch the client, the behavior returns and I have to delete `%appdata%\Bitwarden` to start over.

**Comment by TheP3di** [comment]
Hi guys,
same for me after last Bitwarden Update 

**System:**
- OS:                   Windows 10 Pro
- Version            20H2
- Build Version:  19042.985
- Performance:   Windows Feature Experience Pack 120.2212.2020.0
- Architecture:    X64

**Bitwarden:**
- Version:  1.26.3
- Sehll       11.3.0
- Rendrer 87.0.4280.141
- Node 12.18.3
- Architecture X64

And the same info as in the main post

**Comment by eliykat** [comment]
Hi everyone, we've identified the issue and are working on a fix. Thanks for your patience.

The problem is that certain values are not being saved to local storage correctly. These are read each time the vault is unlocked, so when you unlock your vault, it hits these garbage values and throws this error.

As a workaround, you can open `%AppData%/Bitwarden/data.json` with a text editor and delete the line that starts with `"collapsedGroupings_"`. You may also need to delete the comma at the end of the previous line. Now try unlocking your vault again and see if the issue is fixed.

If this worked, you should avoid collapsing sub-folders or sub-collections. Any time you do that will cause the error to occur again, and you will have to delete this value from `data.json` again.

If this doesn't work, you can simply delete your `%AppData%/Bitwarden` folder - although please note this will clear all your local settings. If you don't want to deal with any of this, you can also just use another client, as the desktop client is the only one experiencing this error.

**Comment by eliykat** [comment]
Follow up: this issue has now been fixed in the new release (1.26.4). You will still need to delete the line in `data.json` that I mentioned in my last comment, but the problem should not reoccur after that.

**Comment by Eraser3** [comment]
Ok, so this "fix" didn't fix existing problems. That's only half a fix.

**Comment by TheP3di** [comment]
I have to agree with @Eraser3 , every non-tech will still have this bug and so it's not a fix. It is your job (Bitwarden Team) to fix this automatically with an update without any extra effort for low-tech people.
Thank you

**Comment by NPadrutt** [comment]
I agree with @TheP3di  and @Eraser3. I don't think that it is a good user experience that 2.5 months after you have a fix for that I encounter this error, have to google it and then manually edit some settings json to fix it.

**Comment by eliykat** [comment]
Hi all, sorry about the rocky upgrade path. We've already gotten most people over this particular roadbump by now, but I'll keep your feedback in mind for future bugfixes. If anyone reading this thread is having trouble finding their local data directory, there is a list [here](https://bitwarden.com/help/article/data-storage/) of potential locations (depending on install source and OS). Upgrading to 1.26.4 or later, and clearing your local data, should resolve the issue. If anyone needs more help, they can contact our Customer Success team [here](https://bitwarden.com/contact/). Next time I'll be sure to provide a smoother off-ramp!

**Comment by neohkl** [comment]
Hi there eliykat: I have just recently started encountering this problem because I am running my linux system from a USB thumbDrives.   Where is Bitwarden/data.json in linux, specifically Linux Mint 20.2 Cinnamon?

On systems running off a regular SSD, I have yet to, despite running Mint, since version 18, i.e. years. 

    OS: Linux Mint 20.2 Cinnamon
    Version 5.0.6
    Architecture: X64
Thx
